replicaCount: 2

imagePullSecrets:
  - name: github

resources:
  limits:
    memory: "4Gi"
    cpu: "500m"
  requests:
    memory: "2Gi"
    cpu: "250m"

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

brandingVolume:
  storageClass: efs-sc
derivativesVolume:
  storageClass: efs-sc
uploadsVolume:
  storageClass: efs-sc

extraVolumeMounts: &volMounts
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/imports
    subPath: imports
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/exports
    subPath: exports
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/public/system
    subPath: public-system
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/public/uploads
    subPath: public-uploads
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/network_files
    subPath: network-files

ingress:
  enabled: true
  hosts:
    - host: '*.hykuup.com'
      paths:
        - path: /
  annotations: {
    kubernetes.io/ingress.class: "nginx",
    nginx.ingress.kubernetes.io/proxy-body-size: "0",
    cert-manager.io/cluster-issuer: letsencrypt-production-dns
  }
  tls:
    - secretName: wildcard-tls-secret
      hosts:
        - '*.hykuup.com'
        
extraEnvVars: &envVars
  - name: BUNDLE_LOCAL__HYKU_KNAPSACK
    value: /app/samvera
  - name: BUNDLE_DISABLE_LOCAL_BRANCH_CHECK
    value: "true"
  - name: CONFDIR
    value: "/app/samvera/hyrax-webapp/solr/conf"
  - name: DB_ADAPTER
    value: postgresql
  - name: DB_ADVISORY_LOCKS
    value: "false"
  - name: DB_PREPARED_STATEMENTS
    value: "false"
  - name: DB_HOST
    value: acid-postgres-cluster-delta.postgres.svc.cluster.local
  - name: DB_NAME
    value: hykuup_production
  - name: DB_PASSWORD
    value: $DB_PASSWORD
  - name: DB_USER
    value: hykuup_production
  - name: DISABLE_SPRING
    value: '1'
  - name: FCREPO_BASE_PATH
    value: /hykuup
  - name: FCREPO_HOST
    value: fcrepo.fcrepo.svc.cluster.local
  - name: FCREPO_REST_PATH
    value: rest
  - name: FCREPO_PATH
    value: /rest
  - name: FCREPO_URL
    value: http://fcrepo.fcrepo.svc.cluster.local:8080/rest
  - name: HYRAX_ANALYTICS
    value: 'false'
  # - name: GOOGLE_ANALYTICS_ID
  #   value: $GOOGLE_ANALYTICS_ID
  # - name: GOOGLE_OAUTH_APP_NAME
  #   value: atla-hyku-production
  # - name: GOOGLE_OAUTH_APP_VERSION
  #   value: '1.0'
  # - name: GOOGLE_OAUTH_PRIVATE_KEY_SECRET
  #   value: $GOOGLE_OAUTH_PRIVATE_KEY_SECRET
  # - name: GOOGLE_OAUTH_PRIVATE_KEY_PATH
  #   value: prod-cred.p12
  # - name: GOOGLE_OAUTH_PRIVATE_KEY_VALUE
  #   value: $GOOGLE_OAUTH_PRIVATE_KEY_VALUE
  # - name: GOOGLE_OAUTH_CLIENT_EMAIL
  #   value: hyku-demo@hyku-demo.iam.gserviceaccount.com
  - name: HYRAX_ACTIVE_JOB_QUEUE
    value: sidekiq
  - name: HYRAX_FITS_PATH
    value: /app/fits/fits.sh
  - name: HYKU_ADMIN_HOST
    value: admin.hykuup.com
  - name: HYKU_ADMIN_ONLY_TENANT_CREATION
    value: 'false'
  - name: HYKU_ALLOW_SIGNUP
    value: 'false'
  - name: HYKU_BULKRAX_ENABLED
    value: 'true'
  - name: HYKU_CONTACT_EMAIL
    value: info@hykuup.com
  - name: HYKU_CONTACT_EMAIL_TO
    value: info@hykuup.com
  - name: HYKU_DEFAULT_HOST
    value: "%{tenant}.hykuup.com"
  - name: HYKU_ENABLED
    value: "true"
  - name: HYKU_FILE_ACL
    value: "true"
  - name: HYKU_MULTITENANT
    value: "true"
  - name: HYKU_ROOT_HOST
    value: hykuup.com
  - name: INITIAL_ADMIN_EMAIL
    value: rob@scientist.com
  - name: INITIAL_ADMIN_PASSWORD
    value: testing123
  - name: HYRAX_USE_SOLR_GRAPH_NESTING
    value: "true"
  - name: IN_DOCKER
    value: "true"
  - name: LD_LIBRARY_PATH
    value: /app/fits/tools/mediainfo/linux
  - name: PASSENGER_APP_ENV
    value: production
  - name: RAILS_CACHE_STORE_URL
    value: redis://:$REDIS_PASSWORD@hykuup-knapsack-production-redis-master:6379/hykuup-hyku
  - name: RAILS_ENV
    value: production
  - name: RAILS_LOG_TO_STDOUT
    value: "true"
  - name: RAILS_MAX_THREADS
    value: "5"
  - name: RAILS_SERVE_STATIC_FILES
    value: "true"
  - name: REDIS_HOST
    value: hykuup-knapsack-production-redis-master
  - name: REDIS_PORT
    value: '6379'
  - name: REDIS_PASSWORD
    value: $REDIS_PASSWORD
  - name: REDIS_URL
    value: redis://:$REDIS_PASSWORD@hykuup-knapsack-production-redis-master:6379/hykuup-hyku
  - name: SECRET_KEY_BASE
    value: $SECRET_KEY_BASE
  - name: SENTRY_DSN
    value: https://eb73063d06644d7e9a2f81713b236d61@o1008683.ingest.sentry.io/6745035
  - name: SENTRY_ENVIRONMENT
    value: production
  - name: SMTP_ADDRESS
    value: email-smtp.us-west-2.amazonaws.com
  - name: SMTP_DOMAIN
    value: hykuup.com
  - name: SMTP_ENABLED
    value: "true"
  - name: SMTP_PASSWORD
    value: $SMTP_PASSWORD
  - name: SMTP_PORT
    value: "587"
  - name: SMTP_STARTTLS
    value: 'true'
  - name: SMTP_TYPE
    value: login
  - name: SMTP_USER_NAME
    value: AKIAJUV5DOPWWUKISN3Q
  - name: SOLR_ADMIN_PASSWORD
    value: $SOLR_ADMIN_PASSWORD
  - name: SOLR_ADMIN_USER
    value: admin
  - name: SOLR_COLLECTION_NAME
    value: hykuup-hyku
  - name: SOLR_CONFIGSET_NAME
    value: hykuup-hyku
  - name: SOLR_HOST
    value: solr-headless.solr
  - name: SOLR_PORT
    value: "8983"
  - name: SOLR_URL
    value: http://admin:$SOLR_ADMIN_PASSWORD@solr-headless.solr:8983/solr/
  - name: SUPPORT_EMAIL
    value: support@notch8.com
  - name: SUPPORT_PASSWORD
    value: testing123
  - name: TEST_USER_EMAIL
    value: user@notch8.com
  - name: TEST_USER_PASSWORD
    value: testing123

securityContext: &secValues
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  runAsUser: 0
podSecurityContext: &podSecValues
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 101
  fsGroup: 101
  fsGroupChangePolicy: 'OnRootMismatch'

worker:
  replicaCount: 1
  resources:
    limits:
      memory: "6Gi"
      cpu: "3"
    requests:
      memory: "3Gi"
      cpu: "1"
  podSecurityContext:
    runAsUser: 1001
    runAsGroup: 101
    fsGroup: 101
    fsGroupChangePolicy: "OnRootMismatch"
  extraVolumeMounts: *volMounts
  extraEnvVars: *envVars
  podSecurityContext: *podSecValues
  securityContext: *secValues

embargoRelease:
  enabled: false
leaseRelease:
  enabled: false

fcrepo:
  enabled: false
postgresql:
  enabled: false

redis:
  persistence:
    enabled: true
    storageClass: ebs
  cluster:
    enabled: false
  password: $REDIS_PASSWORD

solr:
  enabled: false

externalFcrepoHost: fcrepo.fcrepo.svc.cluster.local
externalPostgresql:
  host: acid-postgres-cluster-delta.postgres.svc.cluster.local
  username: hykuup_production
  password: $DB_PASSWORD
  database: hykuup_production

externalSolrPassword: $SOLR_ADMIN_PASSWORD
externalSolrHost: solr.solr.svc.cluster.local
externalSolrUser: admin
externalSolrCollection: "hykuup-hyku"

global:
  hyraxName: hykuup-knapsack-production-hyrax

nginx:
  service:
    port: 80
  enabled: true
  image:
    registry: registry.gitlab.com
    repository: notch8/scripts/bitnami-nginx
    tag: 1.21.5-debian-10-r7
  serverBlock: |-
    upstream rails_app {
      server {{ .Values.global.hyraxName }};
    }
    map ${DOLLAR}status ${DOLLAR}loggable {
        ~^444  0;
        default 1;
    }
    log_format loki 'host=${DOLLAR}host ip=${DOLLAR}http_x_forwarded_for remote_user=${DOLLAR}remote_user [${DOLLAR}time_local] '
                      'request="${DOLLAR}request" status=${DOLLAR}status bytes=${DOLLAR}body_bytes_sent '
                      'referer="${DOLLAR}http_referer" agent="${DOLLAR}http_user_agent" request_time=${DOLLAR}request_time upstream_response_time=${DOLLAR}upstream_response_time upstream_response_length=${DOLLAR}upstream_response_length';
    error_log  /opt/bitnami/nginx/logs/error.log warn;
    #tcp_nopush     on;
    # Cloudflare ips see for refresh
    # https://support.cloudflare.com/hc/en-us/articles/200170786-Restoring-original-visitor-IPs-logging-visitor-IP-addresses
    # update list https://www.cloudflare.com/ips/
    set_real_ip_from 103.21.244.0/22;
    set_real_ip_from 103.22.200.0/22;
    set_real_ip_from 103.31.4.0/22;
    set_real_ip_from 104.16.0.0/13;
    set_real_ip_from 104.24.0.0/14;
    set_real_ip_from 108.162.192.0/18;
    set_real_ip_from 131.0.72.0/22;
    set_real_ip_from 141.101.64.0/18;
    set_real_ip_from 162.158.0.0/15;
    set_real_ip_from 172.64.0.0/13;
    set_real_ip_from 173.245.48.0/20;
    set_real_ip_from 188.114.96.0/20;
    set_real_ip_from 190.93.240.0/20;
    set_real_ip_from 197.234.240.0/22;
    set_real_ip_from 198.41.128.0/17;
    set_real_ip_from 2400:cb00::/32;
    set_real_ip_from 2606:4700::/32;
    set_real_ip_from 2803:f800::/32;
    set_real_ip_from 2405:b500::/32;
    set_real_ip_from 2405:8100::/32;
    set_real_ip_from 2a06:98c0::/29;
    set_real_ip_from 2c0f:f248::/32;
    real_ip_header X-Forwarded-For;
    real_ip_recursive on;
    include /opt/bitnami/nginx/conf/conf.d/*.conf;
    server {
        listen 8080;
        server_name _;
        root /app/samvera/hyrax-webapp/public;
        index index.html;
        client_body_in_file_only clean;
        client_body_buffer_size 32K;
        client_max_body_size 0;
        access_log /opt/bitnami/nginx/logs/access.log loki;
        # if=${DOLLAR}loggable;
        sendfile on;
        send_timeout 300s;
        include /opt/bitnami/nginx/conf/bots.d/ddos.conf;
        include /opt/bitnami/nginx/conf/bots.d/blockbots.conf;
        location ~ (\.php|\.aspx|\.asp) {
          return 404;
        }
        # deny requests for files that should never be accessed
        location ~ /\. {
          deny all;
        }
        location ~* ^.+\.(rb|log)${DOLLAR} {
          deny all;
        }
        # serve static (compiled) assets directly if they exist (for rails production)
        location ~ ^/(assets|packs|fonts|images|javascripts|stylesheets|swfs|system)/ {
          try_files ${DOLLAR}uri @rails;
          # access_log off;
          gzip_static on; # to serve pre-gzipped version
          expires max;
          add_header Cache-Control public;
          # Some browsers still send conditional-GET requests if there's a
          # Last-Modified header or an ETag header even if they haven't
          # reached the expiry date sent in the Expires header.
          add_header Last-Modified "";
          add_header ETag "";
          break;
        }
        # send non-static file requests to the app server
        location / {
          try_files ${DOLLAR}uri @rails;
        }
        location @rails {
          proxy_set_header  X-Real-IP  ${DOLLAR}remote_addr;
          proxy_set_header  X-Forwarded-For ${DOLLAR}proxy_add_x_forwarded_for;
          proxy_set_header Host ${DOLLAR}http_host;
          proxy_redirect off;
          proxy_pass http://rails_app;
        }
    }
